export interface Note {
  id: string;
  title: string;
  content: string; // HTML content generated by AI
  originalText: string;
  tags: string[];
  category:
    | "meeting"
    | "event"
    | "task"
    | "reminder"
    | "idea"
    | "learning"
    | "personal"
    | "work"
    | "other";
  noteType: "text" | "voice";
  createdAt: string;
  updatedAt?: string;

  // Optional metadata extracted by AI (for filtering/display)
  eventDate?: string;
  eventTime?: string;
  location?: string;
  attendees?: string[];
  dueDate?: string;
  priority?: "low" | "medium" | "high" | "urgent";
  reminderDate?: string;
  reminderTime?: string;
  isRecurring?: boolean;
  recurrence?: string;
}

export interface DiscoverItem {
  id: string;
  type: "resurfacing" | "thread" | "explore";
  title: string;
  description: string;
  noteIds?: string[];
  icon: string;
  color: string;
}
